site_name: ShenZhenTrips
nav:
  - 欢迎访问: index.md
  # - 交通: transportation.md
  - 周边闲游: short_trips.md
  - 半日游: half_day.md
  # - 一日游: one_day.md
theme: 
  name: material
  language: zh

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
  - admonition
  - pymdownx.details
  - pymdownx.superfences