site_name: ShenZhenTrips
nav:
  - 欢迎访问: index.md
  - 南山: nanshan.md
  - 福田: futian.md
  - 宝安: baoan.md
  - 盐田: yantian.md
  - 其他: other.md
theme: 
  name: material
  language: zh
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
  plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
  - admonition
  - pymdownx.details
  - pymdownx.superfences

